SYSTEST-9635 - ESLint errors instead of warnings
rdkcentral/firebolt-certification-app pull request #41
Opened 2023-12-05 18:56 UTC by ksentak

# Description
ESLint configuration has been modified. No longer will warnings appear. Now only errors will appear. If errors exist, PRs to dev/main will not be able to be merged.

## JIRA Ticket
Include a link to the JIRA Ticket linked to this PR.
[SYSTEST-9635](https://ccp.sys.comcast.net/browse/SYSTEST-9635)

## Additional Info (Test steps / Steps to reproduce etc.)
Details on how to test the feature

2023-12-08 15:54 UTC, jbigel requested changes

2023-12-08 19:50 UTC, ksentak commented on .github/workflows/lint-and-unit-tests.yml
> +        node-version: [20.x]
Hey we are good to use versions above 16 for FCA. I saw deprecation warnings with the previous action so I figured to update to a newer version

2023-12-08 19:50 UTC, ksentak commented on .github/workflows/lint-and-unit-tests.yml
> +        run: echo "comment=Linting or unit tests failed" >> $GITHUB_ENV
Hey I tried doing this yesterday and was running into a lot of issues. Going to spend some more time now getting this to work.

2023-12-12 16:52 UTC, jbigel approved these changes

2023-12-12 18:11 UTC, merged